### ISSUE TITLE
Allow default messages

### ISSUE THREAD

**Issue by binarykitchen** [tgriesser/create-error#4]
I just saw that I cannot set default messages like that:

```

var UnauthorizedError = createError(ClientError, 'UnauthorizedError', {
    'status':  401,
    'message': 'Unauthorized',
    'details': {}
});
```

In the above example I expect that the following line

```
var err = new UnauthorizedError();
```

would automatically have the message 'Unauthorized' but currently it's undefined.

Any chance you could fix that?

Thx!

**Comment by tgriesser** [comment]
Fixed, thanks!

**Comment by binarykitchen** [comment]
Thx!
