### ISSUE TITLE
Conflict with bluebird

### ISSUE THREAD

**Issue by binarykitchen** [tgriesser/create-error#6]
See https://github.com/petkaantonov/bluebird/issues/291

Looks like this module is rendering the bluebird module unusable (or the other way around) - care to comment here or there on how to fix it?

**Comment by bendrucker** [comment]
I'm with Petka — not seeing how this could be related to create-error or bluebird. Both are used in Bookshelf, for example, without issue. The line you linked to is unrelated. Read the optimization doc—short answer is that `arguments` is a special case.

**Comment by binarykitchen** [comment]
Hmmm, okay, then I have to dig deeper and search for the problem somewhere else.

Regarding the `arguments` case, are you suggesting I should read about it or are you guessing it could be an issue here?

**Comment by bendrucker** [comment]
I only mention it because you linked to it in the other thread. It's a good read but it's not relevant to the particular issue you're seeing. Especially because it covers optimization strategies and not things that would break.

**Comment by binarykitchen** [comment]
exactly my thoughts - just were double checking. all good, thanks. i will try to solve the problem myself ...
